In [25]:
import torch

#Create 2 random tensors of size (2,3) and send them to GPU
t1 = torch.rand(2,3)
t2 = torch.rand(2,3)
t1_g = t1.to("cuda")
t2_g = t2.to("cuda")
print(t1_g)
print(t2_g)

#Perform Matrix multiplication
tmul = torch.matmul(t1_g,t2_g.T)
print(tmul)

#Get max and min values of the 2 random tensors
print(t1_g.max(),t2_g.max())
print(t1_g.min(),t2_g.min())

#Get max and min index values of the 2 random tensors
print(t1_g.argmax(),t2_g.argmax())
print(t1_g.argmin(),t2_g.argmin())

#Random tensor with shape(1,1,1,10) and remove all dimensions with shape 1
t3 = torch.rand(1,1,1,10)
print(t3.shape)
t3 = torch.squeeze(t3)
print(t3.shape)

tensor([[0.1126, 0.1884, 0.9518],
        [0.7832, 0.9079, 0.2917]], device='cuda:0')
tensor([[0.2767, 0.2121, 0.4268],
        [0.6724, 0.6687, 0.8829]], device='cuda:0')
tensor([[0.4773, 1.0419],
        [0.5337, 1.3912]], device='cuda:0')
tensor(0.9518, device='cuda:0') tensor(0.8829, device='cuda:0')
tensor(0.1126, device='cuda:0') tensor(0.2121, device='cuda:0')
tensor(2, device='cuda:0') tensor(5, device='cuda:0')
tensor(0, device='cuda:0') tensor(1, device='cuda:0')


TypeError: rand() received an invalid combination of arguments - got (tuple, seed=int), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
